module.exports = {
  apps: [
    {
      name: "weixin-bot-1",
      cwd: "/opt/weixin-bot-ai/instances/tsja",
      script: "/opt/weixin-bot-ai/bot.js",
      interpreter: "node",
      out_file: "logs/bot.log",
      error_file: "logs/bot-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "weixin-bot-test",
      cwd: "/opt/weixin-bot-ai/instances/test",
      script: "/opt/weixin-bot-ai/bot.js",
      interpreter: "node",
      out_file: "logs/bot.log",
      error_file: "logs/bot-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        NODE_ENV: "development",
      },
    },
    {
      name: "weixin-bot-2",
      cwd: "/opt/weixin-bot-ai/instances/wife",
      script: "/opt/weixin-bot-ai/bot.js",
      interpreter: "node",
      out_file: "logs/bot.log",
      error_file: "logs/bot-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "ocr-service",
      script: "venv/bin/uvicorn",
      args: "main:app --host 127.0.0.1 --port 8765",
      cwd: "/opt/weixin-bot-ai/ocr-service",
      interpreter: "none",
      autorestart: true,
      max_restarts: 10,
      out_file: "logs/out.log",
      error_file: "logs/err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      env: {
        NODE_ENV: "production",
      },
    },
  ],
};
