// 从项目根 constants.js 重新导出，确保测试与代码共享同一套业务常量
export {
  HISTORY_MAX_TURNS, HISTORY_TTL_MS, HISTORY_MAX_CONTENT_LEN,
  FILE_ANCHOR_MAX_CHARS, FILE_ANCHOR_TOTAL_CHARS, FILE_ANCHOR_MAX_TURNS, FILE_ANCHOR_MAX_FILES,
  PENDING_FILE_TTL_MS, RECONNECT_CONFIG, DEFAULT_DOCUMENT_SERVICE_URL,
  COMMANDS_MSG, DEFAULT_PROMPT,
} from "../../constants.js";
